# napcat 配置
host = "192.168.10.102"
port = 4001

prefix = "#"
# 机器人的主人，拥有框架层的最高权限，可以执行所有命令
root = [ 2319289456 ]
# 机器人的管理员，原则上只有插件层管理权限，不能执行框架层的命令
admin = []
# 机器人的插件，插件的加载顺序按照列表的顺序
plugins = [ "demo", "cmd"]

# 日志参数 可选值：debug, info, warn, error
log_level = "info"